import LoginForm from '@/components/LoginForm';

export const metadata = {
  title: 'Sign In | JWT Demo',
  description: 'Generated by create next app',
};

const Login = () => {
  return <LoginForm />;
};
export default Login;
