import RegisterForm from '@/components/RegisterForm';

export const metadata = {
  title: 'Sign Up | JWT Demo',
  description: 'Generated by create next app',
};

const Register = () => {
  return <RegisterForm />;
};
export default Register;
